import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
					Create <span className="text-purple-300">T3</span> App
				</h1>
				<div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
					{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
				</div>
				<h1 className="text-3xl pt-4">Guestbook</h1>
				<p>
					Tutorial for <code>create-t3-app</code>
				</p>
				<div className="py-10">
					<Messages />
				</div>
			</main>
		</>
	);
};

const Messages = () => {
	const { data: messages, isLoading } = trpc.useQuery(["guestbook.getAll"]);

	if (isLoading) return <div>Fetching messages...</div>;

	return (
		<div className="flex flex-col gap-4">
			{messages?.map((msg, index) => {
				return (
					<div key={index}>
						<p>{msg.message}</p>
						<span>- {msg.name}</span>
					</div>
				);
			})}
		</div>
	);
};

export default Home;
